server:
  port: 7001 #端口
  servlet: 
    context-path: /analyzing
  tomcat.uri-encoding: UTF-8
  
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource: 
     type: com.zaxxer.hikari.HikariDataSource
     url: jdbc:oracle:thin:@192.168.13.68:1521/pdb2
     username: statistical
     password: statistical
     hikari:
       driver-class-name: oracle.jdbc.OracleDriver
       ##池中维护的最小空闲连接数
       minimum-idle: 5
       ##池中最大连接数，包括闲置和使用中的连接
       maximum-pool-size: 15
       ##自动提交从池中返回的连接
       auto-commit: true
       ##连接允许在池中闲置的最长时间
       idle-timeout: 30000
       ##连接池的用户定义名称，主要出现在日志记录和JMX管理控制台中以识别池和池配置
       pool-name: DatebookHikariCP
       ##池中连接最长生命周期
       max-lifetime: 18000000
       ##等待来自池的连接的最大毫秒数
       connection-timeout: 30000
       ##验证该连接是否是有效的查询语句
       connection-test-query: select 1 from dual

# ====================MybatisPlus====================
mybatis-plus: 
  #默认就在resources/mapper下，如果要更改目录在这个配置下更改
  mapper-locations: classpath:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.data.entity
  global-config:
    #驼峰下划线转换
    db-column-underline: true
  configuration: 
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#文件解析备份路径
bakPath: D:\ANALYZE_FILE_BAK